feat: compatibility with Laravel 7
designmynight/laravel-mongodb-passport pull request #46
Opened 2020-08-23 23:19 UTC by hypnodev

As report in issue #40 , the package isn't available for Laravel 7. So I've upgraded dependencies and now the library is usable also in version 7 of Laravel.

2020-10-06 20:33 UTC, ZivotSen commented
Awesome package. It would be wonderful if it was available too for Laravel 8.

2020-10-15 16:29 UTC, divine requested changes

2020-10-15 16:29 UTC, divine commented on composer.json
> +        "jenssegers/mongodb": "3.3.* || 3.4.* || 3.5.* || 3.6.* || 4.*",
```suggestion
        "jenssegers/mongodb": "3.3.* || 3.4.* || 3.5.* || 3.6.* || 3.7.*",
```

2020-11-13 03:04 UTC, stharupesh approved these changes

2021-05-07 06:07 UTC, tatyanakoba commented
I have problem when I use this package, I can't to get token when user login from api. Also I can't run php artisan passport:install
I have: php artisan passport:install
Encryption keys already exist. Use the --force option to overwrite them.
Personal access client created successfully.

   TypeError 

  Argument 1 passed to Laravel\Passport\Console\ClientCommand::outputClientDetails() must be an instance of Laravel\Passport\Client, instance of DesignMyNight\Mongodb\Passport\Client given, called in /vendor/laravel/passport/src/Console/ClientCommand.php on line 69

  at vendor/laravel/passport/src/Console/ClientCommand.php:152
    148|      *
    149|      * @param  \Laravel\Passport\Client  $client
    150|      * @return void
    151|      */
  > 152|     protected function outputClientDetails(Client $client)
    153|     {
    154|         $this->line('Client ID: '.$client->id);
    155|         $this->line('Client secret: '.$client->secret);
    156|     }

      +28 vendor frames 
  29  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2021-12-31 09:00 UTC, closed without merging